{{- if .Values.enable_service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
{{- end }}
